Fix obsolete Nerd Font icons
lsd-rs/lsd pull request #830
Opened 2023-03-29 11:36 UTC by nix6839

Replace the old code point with the new code point.
See: https://github.com/ryanoasis/nerd-fonts/releases/tag/v2.3.3

> Material Design Icons
> The Material Design Icons have to move codepoints. Historically we patch them in between F500 - FD46; but part of that range is needed for Chinese and other glyphs. With https://github.com/ryanoasis/nerd-fonts/pull/773 and Plan 5+ of https://github.com/ryanoasis/nerd-fonts/issues/365 their new home will be after F0001. And they grow considerably.

> The v2.3.x release has both, the 'old' and the 'new' codepoints to enable you an easier transision. Please change already now your prompts and other uses to the new codepoints. Release v3.0.0 will finally drop the old codepoints (F500 - FD46).

---
#### TODO

- [x] Use `cargo fmt`
- [x] Add necessary tests
- [x] Add changelog entry
- [x] Update default config/theme in README (if applicable)

2023-03-30 01:33 UTC, zwpaper requested changes
can you help to add some notice under FAQ about this change?

2023-03-30 02:17 UTC, nix6839 commented
> can you help to add some notice under FAQ about this change?

Where is the FAQ? Should I add it to the README section?

2023-03-30 03:40 UTC, nix6839 commented
@zwpaper  I've added a FAQ. I'm not a native English speaker so please let me know if you see anything strange in the FAQs.

2023-03-30 07:59 UTC, zwpaper commented
hi @nix6839, I have one more question, Are the pre-patched fonts updated to this latest v2.3.x version? https://github.com/ryanoasis/nerd-fonts#patched-fonts

looks like the [Hack Nerd](https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/Hack) I was using did not show the expected icons

2023-03-30 10:20 UTC, nix6839 commented
If you look at https://washnix.com/hack-nerd/, it is patched correctly.

The source code of the page: https://github.com/nix6839/hack-nerd/blob/main/index.html

2023-04-22 03:52 UTC, zwpaper commented
hi @nix6839, I double check for the icons, it works like a charm, will merge after CI passed, thanks again!

2023-04-22 04:06 UTC, nix6839 commented
Thank you for your hard work.

2023-04-22 08:11 UTC, merged