feat: Windows safe default permissions (fixes ACL errors/performance)
lsd-rs/lsd pull request #911
Opened 2023-09-25 12:03 UTC by domsleee

Fixes: #200 by implementing #866 as the default permission setting for windows.

### Context
The current default (`--permission rwx`) uses ACL on windows, which can throw errors and has performance problems, described in #200 and also in https://github.com/lsd-rs/lsd/pull/882#issuecomment-1722126112:

> * `GetEffectiveRightsFromAclW` can't access the domain, and os error 1355 is thrown
> * `GetEffectiveRightsFromAclW` works, but it can be very slow when the information about permissions requires files from a remote server [1 second per file for me, worse for others]

### Suggestion
1. A new `--permission attributes` is introduced
2. It is used as the default for windows

### Prior art
* powershell uses it in [Get-ChildItem](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-childitem?view=powershell-7.3#example-1-get-child-items-from-a-file-system-directory)
* [eza](https://github.com/eza-community/eza) uses it as the default for windows (`eza -al`)

#### Checklist

- [x] Use `cargo fmt`
- [x] Add necessary tests
- [ ] Update default config/theme in README (if applicable)
- [ ] Update man page at lsd/doc/lsd.md (if applicable)

2023-10-02 10:10 UTC, domsleee commented
btw - I'm not sure why the `work-in-progress` label is still on this PR.
I think [muniu-bot](https://github.com/apps/muniu-bot) should have removed it when I marked the PR is ready, or perhaps I missed something 😄

Could you please review this one when convenient @zwpaper

2024-01-10 13:10 UTC, roqvist commented
Anyway to help this forward?

2024-01-10 16:47 UTC, zwpaper commented
sorry for the late reply, I will look into this recently

/assign
/milestone v1.1.0

2024-02-04 16:37 UTC, zwpaper requested changes
@domsleee really sorry for the late reply, thanks so much for the great work! it LGTM mostly but only a nit

2024-02-04 16:37 UTC, zwpaper commented on src/meta/mod.rs
> +mod windows_attributes;
how about `#[cfg(windows)]` here, and drop the `#cfg` inside `windows_attributes`?

2024-02-04 16:37 UTC, zwpaper commented on src/meta/windows_attributes.rs
> +#[cfg(windows)]
maybe we can drop all the `#[cfg(windows)]` in this file, if we set it in `mod.rs`

2024-02-16 03:38 UTC, zwpaper commented
hi @domsleee, as it has been some time since you responded, I have pushed a commit to make this PR go forward.

hope you don't mide

2024-02-16 03:47 UTC, merged

2024-02-17 01:52 UTC, domsleee commented
Hi @zwpaper, sorry I missed your review - thanks for reviewing and helping out with this PR 🎉